### ISSUE TITLE
Add pipeline variable `BINSTAR_TOKEN` to enable uploads to tiledb channel

### ISSUE THREAD

**Issue by jdblischak** [TileDB-Inc/m2w64-htslib-feedstock#2]
After the feedstock repo has been registered with Azure (#1), builds will be enabled, but not uploads to anaconda.org. This requires an Azure pipeline variable named `BINSTAR_TOKEN` with an anconda.org token for the account tiledb

1. Generate a token from anaconda.org with scope "Allow all API operations" https://anaconda.org/tiledb/settings/access
1. Go to the Azure pipelines at https://dev.azure.com/TileDB-Inc/CI/_build?view=folders and click on "m2w64-htslib-feedstock"  (I can't predict what `definitionId` Azure will assign this new pipeline, so I can't provide a more exact URL)
1. Click "Edit", then "Variables", then "+ (New variable)"
1. Name it `BINSTAR_TOKEN`, copy-paste the anaconda.org token, select "Keep this value secret", click "OK", click "Save"

**Comment by ihnorton** [comment]
Done

**Comment by jdblischak** [comment]
It worked! 🎉 

https://anaconda.org/tiledb/m2w64-htslib/files?version=1.15.1

**Comment by ihnorton** [comment]
Awesome, looks great!
